Update strings.xml
25huizengek1/ViMusic pull request #22
Opened 2023-11-29 19:32 UTC by siggi1984

Add German language

2023-11-30 11:07 UTC, 25huizengek1 commented
Seems good, but that is unfortunately not how you translate in Android. You’ll have to add overrides for German. That way the default language is still present and untranslated strings will default to that. 

What I am saying is that if I’d merge right now, all of the English would be removed.

For more information on how to translate for Android, please have a look at this: https://developer.android.com/guide/topics/resources/localization#creating-alternatives

2023-11-30 11:14 UTC, 25huizengek1 requested changes
Overall good translations, I think, I’m not particularly fluent in German though, but I’ve added a few comments.

2023-11-30 11:14 UTC, 25huizengek1 commented on app/src/main/res/values/strings.xml
> +    <string name="format_opening_url">Öffne url %1$s</string>
I’m not native German, but I think this should be in a continuous form?

2023-11-30 11:14 UTC, 25huizengek1 commented on app/src/main/res/values/strings.xml
> +    <string name="confirm_hide_song">DMöchten Sie dieses Lied wirklich ausblenden? Die Wiedergabezeit und der Cache werden gelöscht. Diese Aktion ist nicht umkehrbar.</string>
Typo?

2023-11-30 11:14 UTC, 25huizengek1 commented on app/src/main/res/values/strings.xml
> +    <string name="swipe_horizontally_to_close_description">Schließt den Player, wenn Sie auf dem eingeklappten Player nach links/rechts wischen. Nützlich für Benutzer, bei denen der Einhandmodus von
‘\’ escapes nothing here, should be removed?

2023-11-30 15:40 UTC, siggi1984 commented
> Seems good, but that is unfortunately not how you translate in Android. You’ll have to add overrides for German. That way the default language is still present and untranslated strings will default to that.
> 
> What I am saying is that if I’d merge right now, all of the English would be removed.
> 
> For more information on how to translate for Android, please have a look at this: https://developer.android.com/guide/topics/resources/localization#creating-alternatives

Oh sorry, I will try to correct it. The typos too, of course.

2023-11-30 15:46 UTC, 25huizengek1 commented
No problem. Another tip: to cover all German regions / countries you should add a `values-de` directory.

What I meant with regions, these are available in Android:
![image](https://github.com/25huizengek1/ViMusic/assets/50515369/d0b22b87-e456-484b-99f2-a3d62d8f6e22)

It should look like this:
![image](https://github.com/25huizengek1/ViMusic/assets/50515369/2d336fb1-d148-4efa-879c-40a6d38c84bf)

Please only include the strings that are translated, including the strings that stay the same, but not the strings that are still in English. If you are using Android Studio, you could also use the translations editor, as suggested in the screenshot.

2023-11-30 18:27 UTC, siggi1984 commented
I have translated and corrected the strings file. Unfortunately I can't manage to create the folder values-de at github to put the file in there. Can I send you the file and you put it in the folder. I assume that it would not be a problem for you.

2023-11-30 19:15 UTC, closed without merging

2023-12-01 04:44 UTC, siggi1984 commented
Okay, closed this and redid everything once. Hope everything is correct this time.